name: ci

on:
  # diff aware on every PR
  pull_request: {}
  # allow manual triggering
  workflow_dispatch: {}
  # full scan on push to master
  push:
    branches: ["main"]
  # tagging release
  release:
    types:
      - published


jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Bootstrap poetry
        run: |
          curl --location --show-error --silent --output poetry.py https://install.python-poetry.org \
          && echo '66db5477a597b6176202ef77792076057ce50d2c5a2d2d2978c63e1f144d7b95' poetry.py | sha256sum -c \
          && python poetry.py -y \
          && rm poetry.py
      - name: Install dependencies
        run: poetry install
      - name: Compile
        run: poetry run mypy .
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Bootstrap poetry
        run: |
          curl --location --show-error --silent --output poetry.py https://install.python-poetry.org \
          && echo '66db5477a597b6176202ef77792076057ce50d2c5a2d2d2978c63e1f144d7b95' poetry.py | sha256sum -c \
          && python poetry.py -y \
          && rm poetry.py
      - name: Install dependencies
        run: poetry install
      - name: Test
        env:
          TEST_MERGE_API_KEY: ${{ secrets.TEST_MERGE_API_KEY }}
          TEST_MERGE_ATS_ACCOUNT_ID: ${{ secrets.TEST_MERGE_ATS_ACCOUNT_ID }}
          TEST_MERGE_ATS_ACCOUNT_TOKEN: ${{ secrets.TEST_MERGE_ATS_ACCOUNT_TOKEN }}
          TEST_MERGE_HRIS_ACCOUNT_ID: ${{ secrets.TEST_MERGE_HRIS_ACCOUNT_ID }}
          TEST_MERGE_HRIS_ACCOUNT_TOKEN: ${{ secrets.TEST_MERGE_HRIS_ACCOUNT_TOKEN }}
        run: poetry run pytest .

  publish:
    needs: [compile, test]
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Bootstrap poetry
        run: |
          curl --location --show-error --silent --output poetry.py https://install.python-poetry.org \
          && echo '66db5477a597b6176202ef77792076057ce50d2c5a2d2d2978c63e1f144d7b95' poetry.py | sha256sum -c \
          && python poetry.py -y \
          && rm poetry.py
      - name: Install dependencies
        run: poetry install
      - name: Publish to pypi
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry --no-interaction -v publish --build
        env:
          PYPI_TOKEN: ${{ secrets.MERGE_PYPI_TOKEN }}
